# Generated by Django 5.2.17 on 2026-09-29 07:35

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kawasan', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Laporan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('legacy_id', models.BigIntegerField(blank=True, db_index=True, null=True, verbose_name='ID lama (Supabase)')),
                ('tanggal', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('Upaya Pemadaman', 'Upaya Pemadaman'), ('Proses Groundcheck', 'Proses Groundcheck'), ('Sudah Padam', 'Sudah Padam'), ('Perlu Konfirmasi', 'Perlu Konfirmasi'), ('False Hotspot', 'False Hotspot')], db_index=True, default='Upaya Pemadaman', max_length=30)),
                ('lat', models.FloatField(validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)], verbose_name='Lintang')),
                ('lon', models.FloatField(validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='Bujur')),
                ('luas', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Luas terbakar (ha)')),
                ('upaya', models.TextField(blank=True)),
                ('rencana', models.TextField(blank=True, verbose_name='Rencana tindak lanjut')),
                ('personel', models.CharField(blank=True, max_length=500, verbose_name='Jumlah personel')),
                ('kendala', models.TextField(blank=True)),
                ('kebutuhan', models.TextField(blank=True, verbose_name='Kebutuhan / saran')),
                ('laporan', models.TextField(blank=True, verbose_name='Narasi laporan')),
                ('gakkum', models.TextField(blank=True, verbose_name='Penegakan hukum (Gakkum)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('kawasan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='laporan', to='kawasan.kawasan')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'laporan',
                'verbose_name_plural': 'laporan',
                'ordering': ['-tanggal', '-updated_at'],
                'indexes': [models.Index(fields=['kawasan', 'tanggal'], name='laporan_lap_kawasan_e5c697_idx'), models.Index(fields=['tanggal', 'status'], name='laporan_lap_tanggal_b0c57e_idx')],
            },
        ),
    ]
