# Generated by Django 5.2.17 on 2026-09-29 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kawasan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objectid', models.IntegerField(blank=True, db_index=True, null=True, verbose_name='OBJECTID sumber')),
                ('npulau', models.CharField(choices=[('SUMATERA', 'Sumatera'), ('KALIMANTAN', 'Kalimantan'), ('JAWA', 'Jawa'), ('BALI NUSRA', 'Bali Nusra'), ('SULAWESI', 'Sulawesi'), ('MALUKU', 'Maluku'), ('PAPUA', 'Papua')], db_index=True, max_length=20, verbose_name='Pulau')),
                ('nupt', models.CharField(db_index=True, max_length=255, verbose_name='UPT')),
                ('nkws', models.CharField(max_length=255, verbose_name='Kawasan')),
                ('geom', models.JSONField(blank=True, editable=False, null=True)),
                ('geom_simplified', models.JSONField(blank=True, editable=False, null=True)),
                ('min_lon', models.FloatField(blank=True, editable=False, null=True)),
                ('min_lat', models.FloatField(blank=True, editable=False, null=True)),
                ('max_lon', models.FloatField(blank=True, editable=False, null=True)),
                ('max_lat', models.FloatField(blank=True, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'kawasan',
                'verbose_name_plural': 'kawasan',
                'ordering': ['npulau', 'nupt', 'nkws'],
                'constraints': [models.UniqueConstraint(fields=('nupt', 'nkws'), name='uniq_kawasan_nupt_nkws')],
            },
        ),
    ]
