# Generated by Django 5.2.17 on 2026-09-29 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kawasan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotspotSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('date_from', models.DateField(blank=True, null=True)),
                ('date_to', models.DateField(blank=True, null=True)),
                ('fetched', models.PositiveIntegerField(default=0)),
                ('stored', models.PositiveIntegerField(default=0)),
                ('inside_kawasan', models.PositiveIntegerField(default=0)),
                ('success', models.BooleanField(default=False)),
                ('message', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Hotspot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hs_id', models.CharField(max_length=120, unique=True, verbose_name='ID hotspot')),
                ('tanggal', models.DateField(db_index=True)),
                ('waktu', models.CharField(blank=True, max_length=60, verbose_name='Waktu (mentah dari API)')),
                ('confidence', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], db_index=True, max_length=10)),
                ('satelit', models.CharField(blank=True, max_length=60)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('fetched_at', models.DateTimeField(auto_now=True)),
                ('kawasan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hotspots', to='kawasan.kawasan')),
            ],
            options={
                'ordering': ['-tanggal', '-id'],
                'indexes': [models.Index(fields=['tanggal', 'confidence'], name='hotspot_hot_tanggal_bff4ba_idx'), models.Index(fields=['kawasan', 'tanggal'], name='hotspot_hot_kawasan_f4c86d_idx')],
            },
        ),
    ]
